### ISSUE TITLE
Support coloring SVG icons used in CSS

### ISSUE THREAD

**Issue by bwindels** [element-hq/hydrogen-web#173]
It's annoying to have to duplicate icons for different colors. When we have a dark theme or multiple used themes, we'll also want to reuse icons applying different colors. 

Some ideas (none of which have convinced me yet):
 - `mask-image` (won't work in IE11, can we at least fall back to non-colorized image?). This is what element-web does.
 - use service worker to change color in svg source. This won't work for local development which doesn't use a SW, nor IE11.
 - a fallback could be to inline the svg icon source as a custom property (inlined with the postcss plugin for IE11), with other custom properties in the source for the color, which can then be replaced, see https://css-tricks.com/change-color-of-svg-on-hover/#svg-background-images-as-data-urls. This requires a build step and hence won't work for local development.
 - can we work with filters that are supported on IE11. This will not give us all colours but might allow us to make an icon white/black at least? maybe that won't be good enough though ...
 - can't we extend css nowadays with houdini and tricks? maybe we can implement a worklet of some sort that swaps the color in the svg for local development, see https://developer.mozilla.org/en-US/docs/Web/API/Worklet To make it work in production, we could then use the inlining with css custom props?

A good solution will be applicable in just css or at least not require changes to the view code.

**Comment by bwindels** [comment]
paint worklet looks most promising ...

**Comment by jryans** [comment]
> paint worklet looks most promising ...

Seems Chrome only at the moment...? https://developer.mozilla.org/en-US/docs/Web/API/PaintWorklet#Browser_compatibility

**Comment by bwindels** [comment]
Ah crap, I was looking at https://developer.mozilla.org/en-US/docs/Web/API/Worklet for browser support :/

**Comment by jryans** [comment]
Hmm, seems tricky indeed... Perhaps you can get away with filters for IE 11, and use `mask-image` like Element for the rest?

**Comment by bwindels** [comment]
seems like the 3rd option will work with a vite build dev server :+1: 
Perhaps something like this:
```scss
$bike1: "%3Csvg height='24' viewBox='0 0 24 24' width='24' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath fill='";
$bike2: "' d='m5 20.5a3.5 3.5 0 0 1 -3.5-3.5 3.5 3.5 0 0 1 3.5-3.5 3.5 3.5 0 0 1 3.5 3.5 3.5 3.5 0 0 1 -3.5 3.5m0-8.5a5 5 0 0 0 -5 5 5 5 0 0 0 5 5 5 5 0 0 0 5-5 5 5 0 0 0 -5-5m9.8-2h4.2v-1.8h-3.2l-1.94-3.27c-.29-.5-.86-.83-1.46-.83-.47 0-.9.19-1.2.5l-3.7 3.69c-.31.31-.5.71-.5 1.21 0 .63.33 1.16.85 1.47l3.35 2.03v5h1.8v-6.5l-2.25-1.65 2.32-2.35m5.93 13a3.5 3.5 0 0 1 -3.5-3.5 3.5 3.5 0 0 1 3.5-3.5 3.5 3.5 0 0 1 3.5 3.5 3.5 3.5 0 0 1 -3.5 3.5m0-8.5a5 5 0 0 0 -5 5 5 5 0 0 0 5 5 5 5 0 0 0 5-5 5 5 0 0 0 -5-5m-3-7.2c1 0 1.8-.8 1.8-1.8s-.8-1.8-1.8-1.8-1.8.8-1.8 1.8.8 1.8 1.8 1.8z'/%3E%3C/svg%3E";
.icon {
  display: inline-block;
  width: 70px;
  height: 70px;
}
.icon-bike {
  color: red;
  background-image: url("data:image/svg+xml, #{$bike1}red#{$bike2}");
  background-size: cover;
}
.icon-bike:hover,
.icon-bike:focus {
  background-image: url("data:image/svg+xml, #{$bike1}green#{$bike2}");
}
``` 

which with a SCSS/SASS function we could reduce to:
```scss
.icon-bike {
  background-image: colored-svg-url("bike.svg", red);
  background-size: cover;
}
.icon-bike:hover,
.icon-bike:focus {
  background-image: colored-svg-url("bike.svg", green);
}
```
the main downside is that it will repeat the inline svg for every call of the colored-svg-url function. E.g. the image will be inlined twice in the example above. Can't really avoid this I think while staying compatible with IE11 and css url fn does not support string interpolation https://stackoverflow.com/questions/42330075/is-there-a-way-to-interpolate-css-variables-with-url so wouldn't work with other browsers either.

We could even support multiple replaceable colors in an icon like this, with some values to look for configured in the sass plugin, e.g. green is primary color, fushia is secondary color, ... that way the svg can also been viewed and edited in an vector graphics program.

**Comment by MadLittleMods** [comment]
For reference, the current state of things with [`scripts/postcss/css-url-processor.js`](https://github.com/vector-im/hydrogen-web/blob/8b2299852eea7a2bc0e247de6ccdb2676b3e4665/scripts/postcss/css-url-processor.js) and [`scripts/postcss/svg-colorizer.js`](https://github.com/vector-im/hydrogen-web/blob/8b2299852eea7a2bc0e247de6ccdb2676b3e4665/scripts/postcss/svg-colorizer.js) from https://github.com/vector-im/hydrogen-web/pull/707, you can colorize SVG's used in CSS via query parameters:

```css
button {
    background: url("/home/foo/bar/cool.svg?primary=blue&secondary=green");
}
```

```svg
<svg height="100" width="100">
    <rect width="100" height="100" fill="#ff00ff">primary color is #ff00ff and will be replaced blue</rect>
    <rect width="50" height="50" fill="#00ffff">secondary color is #00ffff and will be replaced by green</rect>
</svg>
```
