### ISSUE TITLE
defaultHomeServer in config.json not honoured

### ISSUE THREAD

**Issue by heylix** [element-hq/hydrogen-web#324]
docker-compose.yml:

```yaml
  h2:
    image: hydrogen-dev:latest
    networks:
      - public
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.h2.loadbalancer.server.port=3000"
      - "traefik.http.routers.h2.rule=Host(`h2.tilde.fun`)"
      - "traefik.http.routers.h2.tls=true"
      - "traefik.http.routers.h2.tls.certResolver=le"
    volumes:
      - "./h2/config.json:/code/assets/config.json:ro"
```

./h2/config.json:

```json
{
  "push": {
    "appId": "io.element.hydrogen.web",
    "gatewayUrl": "https://matrix.org",
    "applicationServerKey": "BC-gpSdVHEXhvHSHS0AzzWrQoukv2BE7KzpoPO_FfPacqOo3l1pdqz7rSgmB04pZCWaHPz7XRe6fjLaC-WPDopM"
  },
  "defaultHomeServer": "tilde.fun"
}
```

Homeserver shows as matrix.org still:

![grafik](https://user-images.githubusercontent.com/36211486/114194373-b39fea00-994f-11eb-8be0-8a4c6d571a65.png)

If you go to h2.tilde.fun/assets/config.json you get the config.json I mapped, so…

EDIT: oh, the index.html still has the `defaultHomeServer: "matrix.org"` key from 
https://github.com/vector-im/hydrogen-web/commit/110f0821f05a56708a4926a106635395b5ffa37c ;)

If you remove that line, the homeserver is "undefined". If you add "tilde.fun" it doesn't recognise that the "real" homeserver is synapse.tilde.fun (so it doesn't check `.well-known` directories?).
